import {
  Accessibility,
  Battery,
  Bus,
  CalendarCheck,
  Car,
  Cctv,
  Coffee,
  ConciergeBell,
  CreditCard,
  FastForward,
  LampCeiling,
  Luggage,
  Mailbox,
  Plug,
  PlugZap,
  Shield,
  ShieldPlus,
  ShoppingBag,
  Umbrella,
  Waves,
  Wifi,
  Zap,
} from "lucide-react";

export const parkingSpots = [
  {
    title: "Downtown Secure Parking",
    description:
      "24/7 secured parking facility in the heart of downtown with CCTV surveillance",
    rating: 4.5,
    amenities: [
      { name: "Security Camera", icon: Cctv },
      { name: "24/7 Access", icon: CalendarCheck },
      { name: "EV Charging", icon: PlugZap },
      { name: "Covered Parking", icon: Umbrella },
    ],
    image: "downtown-parking.jpg",
    hourlyPrice: 5.99,
    type: "parking",
    imageUrl: "/parking-spots/location-1.jpg",
    address: "123 Main St, Downtown",
  },
  {
    title: "Central Station Parking",
    description:
      "Convenient parking near central station with direct access to public transport",
    rating: 4.2,
    amenities: [
      { name: "Wheelchair Access", icon: Accessibility },
      { name: "Public Transport", icon: Bus },
      { name: "Well Lit", icon: LampCeiling },
    ],
    image: "station-parking.jpg",
    hourlyPrice: 4.5,
    type: "parking",
    imageUrl: "/parking-spots/location-2.jpg",
    address: "456 Central Ave, Near Station",
  },
  {
    title: "Shopping Mall Premium Parking",
    description:
      "Premium parking spaces with direct mall access and valet service",
    rating: 4.8,
    amenities: [
      { name: "Valet Service", icon: ConciergeBell },
      { name: "Car Wash", icon: Waves },
      { name: "Mall Access", icon: Mailbox },
      { name: "Weather Protected", icon: Umbrella },
    ],
    image: "mall-parking.jpg",
    hourlyPrice: 7.99,
    type: "parking",
    imageUrl: "/parking-spots/location-3.jpg",
    address: "789 Mall Rd, Shopping District",
  },
  {
    title: "Airport Long-Term Parking",
    description:
      "Secure long-term parking with shuttle service to airport terminals",
    rating: 4.3,
    amenities: [
      { name: "Shuttle Service", icon: Car },
      { name: "Security Patrol", icon: ShieldPlus },
      { name: "Luggage Help", icon: Luggage },
    ],
    image: "airport-parking.jpg",
    hourlyPrice: 3.99,
    type: "parking",
    imageUrl: "/parking-spots/location-4.jpg",
    address: "101 Airport Blvd, Near Terminals",
  },
  {
    title: "Tech Park Underground Parking",
    description:
      "Modern parking facility with smart parking assistance and EV charging",
    rating: 4.6,
    amenities: [
      { name: "Smart Parking", icon: Car },
      { name: "EV Charging", icon: PlugZap },
      { name: "WiFi Access", icon: Wifi },
      { name: "24/7 Security", icon: Shield },
    ],
    image: "tech-park-parking.jpg",
    hourlyPrice: 6.5,
    type: "parking",
    imageUrl: "/parking-spots/location-5.jpg",
    address: "202 Tech Park Dr, Tech District",
  },
  {
    title: "Hospital Visitors Parking",
    description:
      "Priority parking for hospital visitors with wheelchair accessibility",
    rating: 4.4,
    amenities: [
      { name: "Wheelchair Access", icon: Accessibility },
      { name: "24/7 Access", icon: CalendarCheck },
      { name: "Security Camera", icon: Cctv },
    ],
    image: "hospital-parking.jpg",
    hourlyPrice: 4.99,
    type: "parking",
    imageUrl: "/parking-spots/location-6.jpg",
    address: "303 Hospital Rd, Medical Center",
  },
];

export const chargingStations = [
  {
    title: "SuperCharge Downtown Hub",
    description:
      "Fast charging station with multiple connector types and amenities",
    rating: 4.7,
    status: "Available",
    connectorTypes: ["CCS", "CHAdeMO", "Type 2"],
    powerOutput: 150,
    amenities: [
      { name: "Fast Charging", icon: Zap },
      { name: "Cafe", icon: Coffee },
      { name: "Secure Payment", icon: CreditCard },
      { name: "Free Wifi", icon: Wifi },
    ],
    pricePerKwh: 0.45,
    type: "charging",
    imageUrl: "/charging-spots/charge-1.jpg",
    occupancy: 2,
    totalSpots: 6,
    address: "123 Charging St, Downtown",
  },
  {
    title: "Mall Express Charging",
    description: "Shop while you charge with premium retail access",
    rating: 4.5,
    status: "Available",
    connectorTypes: ["CCS", "Type 2"],
    powerOutput: 120,
    amenities: [
      { name: "Shopping Access", icon: ShoppingBag },
      { name: "Fast Charging", icon: FastForward },
      { name: "24/7 Security", icon: Shield },
    ],
    pricePerKwh: 0.38,
    type: "charging",
    imageUrl: "/charging-spots/charge-2.jpg",
    occupancy: 1,
    totalSpots: 4,
    address: "456 Mall Rd, Shopping District",
  },
  {
    title: "Highway QuickCharge Station",
    description: "Ultra-fast charging for long-distance travelers",
    rating: 4.8,
    status: "Busy",
    connectorTypes: ["CCS", "CHAdeMO"],
    powerOutput: 350,
    amenities: [
      { name: "Ultra-Fast", icon: Zap },
      { name: "Battery Service", icon: Battery },
      { name: "Multiple Plugs", icon: Plug },
    ],
    pricePerKwh: 0.52,
    type: "charging",
    imageUrl: "/charging-spots/charge-3.jpg",
    occupancy: 4,
    totalSpots: 4,
    address: "789 Highway Rd, Near Exit 12",
  },
  {
    title: "Green Energy Hub",
    description: "Solar-powered charging station with premium amenities",
    rating: 4.9,
    status: "Available",
    connectorTypes: ["CCS", "Type 2"],
    powerOutput: 250,
    amenities: [
      { name: "Solar Powered", icon: Zap },
      { name: "Premium Lounge", icon: Coffee },
      { name: "Battery Health Check", icon: Battery },
      { name: "WiFi", icon: Wifi },
    ],
    pricePerKwh: 0.42,
    type: "charging",
    imageUrl: "/charging-spots/charge-4.jpg",
    occupancy: 1,
    totalSpots: 8,
    address: "101 Green Energy Blvd, Eco Park",
  },
  {
    title: "Business District Chargers",
    description: "Quick charging solution for business professionals",
    rating: 4.6,
    status: "Available",
    connectorTypes: ["CCS", "Type 2"],
    powerOutput: 180,
    amenities: [
      { name: "Fast Charging", icon: FastForward },
      { name: "Workspace", icon: Plug },
      { name: "Secure Access", icon: Shield },
    ],
    pricePerKwh: 0.48,
    type: "charging",
    imageUrl: "/charging-spots/charge-5.jpg",
    occupancy: 3,
    totalSpots: 6,
    address: "202 Business St, Financial District",
  },
];

export const iconMappings = [
  { name: "Security Camera", icon: Cctv },
  { name: "24/7 Access", icon: CalendarCheck },
  { name: "EV Charging", icon: PlugZap },
  { name: "Covered Parking", icon: Umbrella },
  { name: "Wheelchair Access", icon: Accessibility },
  { name: "Public Transport", icon: Bus },
  { name: "Well Lit", icon: LampCeiling },
  { name: "Valet Service", icon: ConciergeBell },
  { name: "Car Wash", icon: Waves },
  { name: "Mall Access", icon: Mailbox },
  { name: "Weather Protected", icon: Umbrella },
  { name: "Shuttle Service", icon: Car },
  { name: "Security Patrol", icon: ShieldPlus },
  { name: "Luggage Help", icon: Luggage },
  { name: "Smart Parking", icon: Car },
  { name: "WiFi Access", icon: Wifi },
  { name: "24/7 Security", icon: Shield },
  { name: "Fast Charging", icon: Zap },
  { name: "Cafe", icon: Coffee },
  { name: "Secure Payment", icon: CreditCard },
  { name: "Shopping Access", icon: ShoppingBag },
  { name: "Ultra-Fast", icon: FastForward },
  { name: "Battery Service", icon: Battery },
  { name: "Multiple Plugs", icon: Plug },
  { name: "Solar Powered", icon: Zap },
  { name: "Premium Lounge", icon: Coffee },
  { name: "Battery Health Check", icon: Battery },
  { name: "Workspace", icon: Plug },
  { name: "Secure Access", icon: Shield },
];
